### ISSUE TITLE
setting environment variables

### ISSUE THREAD

**Issue by ghost** [pangeo-data/cookiecutter-pangeo-binder#15]
I hope this is an OK place to ask this question...I have made a simple pangeo binder. I copy in some binaries using `curl` in my `postBuild` script. But...I can't figure out how to add their location to the system path using an environment variable. Is that even possible?

Many thanks!

**Comment by jhamman** [comment]
Have you tried setting the `PATH` variable in your postBuild script?

**Comment by ghost** [comment]
Yep - that's what I've been trying using an `export` statement. But when I look at the `PATH` variable in the terminal through the binder browser it has not been updated. Is there another way?

**Comment by jhamman** [comment]
You could try setting it in the `start` file which is executed at launch (not build).

**Comment by ghost** [comment]
thanks @jhamman! I rocked it in the `start` file and worked great!
