### ISSUE TITLE
This repository lacks a setup.py

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/cookiecutter-pangeo-binder#8]
@jhamman is it possible that you have this on your local machine and that it wasn't checked into git?

**Comment by jhamman** [comment]
@mrocklin - AFAIK, we don't need a setup.py here. I just ran the setup instructions locally and things seem to work for me. Maybe you can explain a bit more what you are trying to do.

**Comment by mrocklin** [comment]
Ah, indeed.  Trying now.  Thanks.
